services:
  - type: web
    name: springboot-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
    autoDeploy: true
    healthCheckPath: /
    serviceDetails:
      - key: port
        value: 8080
